### ISSUE TITLE
Trained networks

### ISSUE THREAD

**Issue by coloss** [microsoft/FaceSynthetics#11]
Thanks for this great work! Do you also plan to release the nn models you trained for your publication?

**Comment by iperov** [comment]
![python_2021-10-13_09-08-27](https://user-images.githubusercontent.com/8076202/137072858-e852cc80-3e5b-4741-903f-bc43494e5edc.png)

the beard will noise anyway

https://user-images.githubusercontent.com/8076202/137072871-fe78a7cf-d537-419c-a3b4-971f0a1d6fd7.mp4

currently dataset is not usable, because we have no skin label under the beard.

**Comment by TadasBaltrusaitis** [comment]
Thanks for your interest in our FaceSynthetics dataset. This dataset is intended to accompany the ICCV paper submission and to help reproduce our results for face parsing and sparse landmark detection. The current release is as-is and we are not planning to include the trained networks. Your suggestions are appreciated, and we will take them into consideration for any future dataset releases.
