### ISSUE TITLE
floating point hair mask

### ISSUE THREAD

**Issue by iperov** [microsoft/FaceSynthetics#13]
current hair segmentation is useless
look at sample
https://user-images.githubusercontent.com/8076202/137632951-f00bfee7-69df-4c55-9484-1d5c32be821c.mp4

Looks like you removed hair pixels with < 0.5 opacity .

we need hair mask as fp value, so the developer will decide either to include all hair, or clip by certain opacity.

**Comment by GilesBathgate** [comment]
I believe this request is similar in essence to #42

**Comment by friggog** [comment]
As the format for segmentation masks that was approved for release is an integer indexed image we have necessarily had to threshold the hair - in most cases this has little impact, although for very short hair can be problematic as you've identified. Unfortunately we haven't got approval to release any other ground truth types or images, only for what is here currently. Thanks for highlighting this though, if we release another dataset with segmentation masks in the future we will make sure to keep this in mind so that we can make it as useful as possible - as you say the threshold should be controlled dependent on the downstream task which isn't possible here
