### ISSUE TITLE
Face annotation conversion

### ISSUE THREAD

**Issue by moonlight99** [microsoft/FaceSynthetics#19]
Greetings!
Thanks for sharing such an inspirational results!

I'm setting up a set of training experiments with the dataset. I found, that landmarks' annotation format does not directly maps to 300W, WFLW, etc.:
1. Different keypoints positions.
2. Invisible landmarks are drawn as direct projections. In contrast, other annotation types supposes landmarks movement to the edge of visible part of the face.

So do you have a plan to a) provide a converter to the mentioned benchmarks or b) share a 3D landmarks annotation? 
I would be very grateful.

**Sample from your dataset:**
![Microsoft_3](https://user-images.githubusercontent.com/31445871/140375300-c85a3f39-3512-4d17-9455-be46f9754d6c.png)

**Example from WFLW dataset:**
![WFLW_4](https://user-images.githubusercontent.com/31445871/140375017-914dcf85-d455-4589-bacc-fbbdee9653f7.png)

**Comment by TadasBaltrusaitis** [comment]
Please see Section 4.3 of our [paper](https://arxiv.org/pdf/2109.15102.pdf), specifically the label adaptation part. We train an additional network that maps from our landmark convention to target dataset one.

We do this because the conventions differ (both because different landmarks are used and because the semantics of landmarks differ)
