### ISSUE TITLE
6d pose annotations

### ISSUE THREAD

**Issue by DaWelter** [microsoft/FaceSynthetics#35]
Hi!
First, I would also like to express my admiration for this work.

Then please add my request for releasing 6d pose information. I think it would be interesting to train estimators for 6d pose on your dataset due to having perfect ground truth data in contrast to training on 300w-lp.

Thank you

Michael

**Comment by rlczddl** [comment]
+1

**Comment by jmbuena** [comment]
Given landmarks are perfect, you can use a POSIT or PnP algorithm to compute almost perfect 3D pose from them. You need also a general 3D rigid model of the face (e.g. the one provided in AFLW dataset). We did this from manual annotated landmarks of the face in different datasets and it worked well:

Roberto Valle, José Miguel Buenaposada, Luis Baumela:
Multi-Task Head Pose Estimation in-the-Wild. IEEE Trans. Pattern Anal. Mach. Intell. 43(8): 2874-2881 (2021)

I guess that with perfect landmarks the pose pseudo-labels will be almost perfect.

**Comment by DaWelter** [comment]
@jmbuena Your papers is really cool. But the appeal of this dataset are the perfect labels. As @rlczddl wrote, fitting a face model would spoil that.

**Comment by jmbuena** [comment]
@rlczddl, I agree that the perfect 3D labels would be nice, but if the FaceSynthetics authors do not provide them, you still can get this pseudo labels with PnP.

We used a generic mean face. Yo can find here the face models we used for different number of landmarks:
https://github.com/bobetocalo/faces_framework/tree/master/headpose/posit/data

In any case, we got our average face model from AFLW dataset (I think the model was in the companion software).

Hope that helps.

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.

@jmbuena's suggestion is a good one and should give reasonably good results, although it is true this will have some noise which kind of undermines the point... You could also try using a subset of points which will define a plane that is minimally impacted by changes in the face identity and expression - for example the eye corners and the tragia define a plane whose normal is pretty much always perpendicular to the gaze direction. Taking the cross product of this normal and the vector between the eye corners should give you a quite reliable gaze vector that is less impacted by identity and expression than using PnP with the whole face landmarks.

**Comment by jmbuena** [comment]
Thanks for the update @friggog. 

I forgot to mention that when you use POSIT or PnP, you have to use only the almost rigid points of the face (as @friggog suggest).

**Comment by dodobyte** [comment]
Estimating depth from 2D landmarks doesn't work with extreme angles due to pose ambiguity. I've tried different methods like PnP but none of them worked as the problem is ill posed.

Here's a sample that shows the ambiguity, landmark 0 is on the near or far side of the face? It changes the pose significantly.
![](https://i.imgur.com/oKPgVpS.png)

My solution was to fit the camera and pose parameters of the [FLAME](https://flame.is.tue.mpg.de/index.html) model using the 2D landmarks, which actually worked great. This method elliminates the ambiguity because the FLAME landmarks (which are generated directly from 3D mesh) has the same order and correspondance to this datasets landmarks (first 68). So there's only one head pose for the FLAME model to produce this particular landmark projection (order matters ofc.)

Anyhow, if anyone needs it, I can give accurate 3D landmarks for the dataset (except the 2 iris points). X and Y coordinates will be the same as the current annotations, just depth will be added. Iris points' depth can be estimated as the average of eye landmarks.
